const aiArticles = [
  {
    "type": "כלי AI חדש",
    "category": "כלי AI חדש",
    "source_site": "crescendo.ai",
    "source": "crescendo.ai",
    "site": "crescendo.ai",
    "title": "Agent Studio ו-MCP Server: סוכני AI ארגוניים בלחיצת כפתור",
    "description": "רוצים לפרוס סוכני AI בתוך Slack, Microsoft Teams ומודלים חיצוניים? Agent Studio הופך מערכי נתונים וחוקים עסקיים לסוכנים פעילים, בעוד MCP Server מחבר אותם לכלי העבודה היומיומיים. הגרסה כוללת גם אפשרויות פריסה מקומית (on-premises) ותכונות ממשל (governance) לטיפול בדאגות אבטחה ועלויות ארגוניות.",
    "summary": "רוצים לפרוס סוכני AI בתוך Slack, Microsoft Teams ומודלים חיצוניים? Agent Studio הופך מערכי נתונים וחוקים עסקיים לסוכנים פעילים, בעוד MCP Server מחבר אותם לכלי העבודה היומיומיים. הגרסה כוללת גם אפשרויות פריסה מקומית (on-premises) ותכונות ממשל (governance) לטיפול בדאגות אבטחה ועלויות ארגוניות.",
    "audience": "מפתחים וארגונים",
    "target_audience": "מפתחים וארגונים",
    "target": "מפתחים וארגונים",
    "link": "https://www.crescendo.ai/news/latest-ai-news-and-updates",
    "url": "https://www.crescendo.ai/news/latest-ai-news-and-updates"
  },
  {
    "type": "אפליקציית בריאות AI",
    "category": "אפליקציית בריאות AI",
    "source_site": "crescendo.ai",
    "source": "crescendo.ai",
    "site": "crescendo.ai",
    "title": "MyLabcorp: אפליקציה רפואית מבוססת OpenAI שמפענחת תוצאות מעבדה",
    "description": "Labcorp השיקה את MyLabcorp – אפליקציה ניידת תואמת HIPAA המשתמשת במודלי ה-reasoning של OpenAI. המשתמשים יכולים לשוחח עם AI כדי להבין תוצאות בדיקות דם, לעקוב אחר מגמות בריאות לאורך זמן, ולגשת לתוכן חינוכי מאושר קלינית בתחומים כמו בריאות לב-כלייתית.",
    "summary": "Labcorp השיקה את MyLabcorp – אפליקציה ניידת תואמת HIPAA המשתמשת במודלי ה-reasoning של OpenAI. המשתמשים יכולים לשוחח עם AI כדי להבין תוצאות בדיקות דם, לעקוב אחר מגמות בריאות לאורך זמן, ולגשת לתוכן חינוכי מאושר קלינית בתחומים כמו בריאות לב-כלייתית.",
    "audience": "צרכנים ואנשי מקצוע רפואי",
    "target_audience": "צרכנים ואנשי מקצוע רפואי",
    "target": "צרכנים ואנשי מקצוע רפואי",
    "link": "https://www.crescendo.ai/news/latest-ai-news-and-updates",
    "url": "https://www.crescendo.ai/news/latest-ai-news-and-updates"
  },
  {
    "type": "עדכון פלטפורמה",
    "category": "עדכון פלטפורמה",
    "source_site": "blog.google",
    "source": "blog.google",
    "site": "blog.google",
    "title": "Google מרץ 2026: Gemini מתרחב לכל מקום – Docs, Sheets, Maps ועוד",
    "description": "גוגל הכריזה על גל עדכונים מרשים: הרחבת Search Live, שיפורי AI ב-Docs, Sheets, Slides ו-Drive, שדרוגי Google Maps, הרחבת Personal Intelligence וכלים חדשים למעבר ל-Gemini. הסוויט הארגוני של גוגל הופך לחכם יותר בכל נקודת מגע.",
    "summary": "גוגל הכריזה על גל עדכונים מרשים: הרחבת Search Live, שיפורי AI ב-Docs, Sheets, Slides ו-Drive, שדרוגי Google Maps, הרחבת Personal Intelligence וכלים חדשים למעבר ל-Gemini. הסוויט הארגוני של גוגל הופך לחכם יותר בכל נקודת מגע.",
    "audience": "משתמשי Google Workspace ואנשי מקצוע",
    "target_audience": "משתמשי Google Workspace ואנשי מקצוע",
    "target": "משתמשי Google Workspace ואנשי מקצוע",
    "link": "https://blog.google/innovation-and-ai/technology/ai/google-ai-updates-march-2026/",
    "url": "https://blog.google/innovation-and-ai/technology/ai/google-ai-updates-march-2026/"
  },
  {
    "type": "עדכון פלטפורמה",
    "category": "עדכון פלטפורמה",
    "source_site": "blog.google",
    "source": "blog.google",
    "site": "blog.google",
    "title": "Google אפריל 2026: מחולל וידאו חינמי, מדריך קוד אישי ועוזרי מחקר מתקדמים",
    "description": "גוגל ממשיכה לדחוף את גבולות ה-AI הנגיש: השקת מחולל וידאו חינמי, מדריך קוד אישי מבוסס AI, ועוזרי מחקר מתקדמים – כל זאת כדי להפוך AI לשימושי יותר, מפרויקטי בית ספר ועד משימות עסקיות מקצועיות.",
    "summary": "גוגל ממשיכה לדחוף את גבולות ה-AI הנגיש: השקת מחולל וידאו חינמי, מדריך קוד אישי מבוסס AI, ועוזרי מחקר מתקדמים – כל זאת כדי להפוך AI לשימושי יותר, מפרויקטי בית ספר ועד משימות עסקיות מקצועיות.",
    "audience": "סטודנטים, מפתחים ואנשי עסקים",
    "target_audience": "סטודנטים, מפתחים ואנשי עסקים",
    "target": "סטודנטים, מפתחים ואנשי עסקים",
    "link": "https://blog.google/innovation-and-ai/technology/ai/google-ai-updates-april-2026/",
    "url": "https://blog.google/innovation-and-ai/technology/ai/google-ai-updates-april-2026/"
  },
  {
    "type": "השקת כלי AI",
    "category": "השקת כלי AI",
    "source_site": "blog.google",
    "source": "blog.google",
    "site": "blog.google",
    "title": "Google I/O 2026: 100 הכרזות – עריכת תמונות חכמה ו-Google Pics בדרך",
    "description": "בין 100 ההכרזות של Google I/O 2026 בולטת כלי עריכת תמונות חדש עם segmentation של אובייקטים, עריכת טקסט ותרגום, ואינטגרציה עם Workspace. בנוסף, Google Pics – כלי תמונות חדש – יושק בקיץ למנויי AI Pro ו-Ultra, ובתצוגה מקדימה ללקוחות Workspace עסקיים.",
    "summary": "בין 100 ההכרזות של Google I/O 2026 בולטת כלי עריכת תמונות חדש עם segmentation של אובייקטים, עריכת טקסט ותרגום, ואינטגרציה עם Workspace. בנוסף, Google Pics – כלי תמונות חדש – יושק בקיץ למנויי AI Pro ו-Ultra, ובתצוגה מקדימה ללקוחות Workspace עסקיים.",
    "audience": "יוצרים, מפתחים ומשתמשי Workspace",
    "target_audience": "יוצרים, מפתחים ומשתמשי Workspace",
    "target": "יוצרים, מפתחים ומשתמשי Workspace",
    "link": "https://blog.google/innovation-and-ai/technology/ai/google-io-2026-all-our-announcements/",
    "url": "https://blog.google/innovation-and-ai/technology/ai/google-io-2026-all-our-announcements/"
  },
  {
    "type": "עדכון דפדפן",
    "category": "עדכון דפדפן",
    "source_site": "mashable.com",
    "source": "mashable.com",
    "site": "mashable.com",
    "title": "SynthID ב-Chrome: גוגל מביאה זיהוי תוכן AI ישירות לדפדפן",
    "description": "גוגל משלבת את טכנולוגיית SynthID של DeepMind ישירות ב-Chrome – כלי לסימון ואימות תוכן שנוצר על ידי AI. הצעד הזה מציב את Chrome בחזית מאבק ה-Deepfakes ותוכן מזויף, ומספק שכבת אמון חיונית לגולשים ולמפתחים כאחד.",
    "summary": "גוגל משלבת את טכנולוגיית SynthID של DeepMind ישירות ב-Chrome – כלי לסימון ואימות תוכן שנוצר על ידי AI. הצעד הזה מציב את Chrome בחזית מאבק ה-Deepfakes ותוכן מזויף, ומספק שכבת אמון חיונית לגולשים ולמפתחים כאחד.",
    "audience": "מפתחים, עיתונאים ומשתמשי אינטרנט כלליים",
    "target_audience": "מפתחים, עיתונאים ומשתמשי אינטרנט כלליים",
    "target": "מפתחים, עיתונאים ומשתמשי אינטרנט כלליים",
    "link": "https://me.mashable.com/tech/71616/google-io-every-new-feature-coming-to-chrome-including-two-ai-detection-tools",
    "url": "https://me.mashable.com/tech/71616/google-io-every-new-feature-coming-to-chrome-including-two-ai-detection-tools"
  },
  {
    "type": "עדכון מודל AI",
    "category": "עדכון מודל AI",
    "source_site": "iteache.com",
    "source": "iteache.com",
    "site": "iteache.com",
    "title": "מאי 2026: GPT-5.5, DeepSeek V4, Meta Superintelligence ו-Microsoft Agent 365 – חודש שישנה את המפה",
    "description": "מאי 2026 הוא חודש שיכתב בהיסטוריה של ה-AI: GPT-5.5 מגיע עם שימוש מובנה במחשב (native computer use), DeepSeek V4 מתמחר מתחת לכל מודל frontier אחר, Meta משיקה את המודל הראשון של Superintelligence Labs, ו-Microsoft מציגה את Agent 365 – פלטפורמת סוכנים ארגונית חדשה.",
    "summary": "מאי 2026 הוא חודש שיכתב בהיסטוריה של ה-AI: GPT-5.5 מגיע עם שימוש מובנה במחשב (native computer use), DeepSeek V4 מתמחר מתחת לכל מודל frontier אחר, Meta משיקה את המודל הראשון של Superintelligence Labs, ו-Microsoft מציגה את Agent 365 – פלטפורמת סוכנים ארגונית חדשה.",
    "audience": "מפתחים, חוקרי AI ומנהלי טכנולוגיה",
    "target_audience": "מפתחים, חוקרי AI ומנהלי טכנולוגיה",
    "target": "מפתחים, חוקרי AI ומנהלי טכנולוגיה",
    "link": "https://iteache.com/resources/new-ai-tools-launched-may-2026",
    "url": "https://iteache.com/resources/new-ai-tools-launched-may-2026"
  },
  {
    "type": "כלי AI לפיתוח",
    "category": "כלי AI לפיתוח",
    "source_site": "fyxer.com",
    "source": "fyxer.com",
    "site": "fyxer.com",
    "title": "Cursor מגרסה חדשה: 8 סוכני AI במקביל, עורך ויזואלי וגישור בין עיצוב לקוד",
    "description": "Cursor משדרגת את חוויית הפיתוח עם תיאום multi-agent – עד 8 סוכני AI עובדים בו-זמנית על חלקים שונים של ה-codebase. בנוסף, עורך ויזואלי חדש מגשר בין עיצוב לקוד, ומאפשר למפתחים לעבוד מהר יותר ובצורה חכמה יותר מאי פעם.",
    "summary": "Cursor משדרגת את חוויית הפיתוח עם תיאום multi-agent – עד 8 סוכני AI עובדים בו-זמנית על חלקים שונים של ה-codebase. בנוסף, עורך ויזואלי חדש מגשר בין עיצוב לקוד, ומאפשר למפתחים לעבוד מהר יותר ובצורה חכמה יותר מאי פעם.",
    "audience": "מפתחי תוכנה ומהנדסים",
    "target_audience": "מפתחי תוכנה ומהנדסים",
    "target": "מפתחי תוכנה ומהנדסים",
    "link": "https://www.fyxer.com/blog/new-ai-tools",
    "url": "https://www.fyxer.com/blog/new-ai-tools"
  },
  {
    "type": "כלי AI לעסקים",
    "category": "כלי AI לעסקים",
    "source_site": "marketingprofs.com",
    "source": "marketingprofs.com",
    "site": "marketingprofs.com",
    "title": "Adobe PDF Spaces: מסמכים סטטיים מתים – ברוכים הבאים לחוויות מידע אינטראקטיביות",
    "description": "Adobe מהפכת את עולם ה-PDF with PDF Spaces – סביבת עבודה חדשה המשלבת קבצים, הערות וקישורים לחוויות אינטראקטיביות עם עוזרי AI מותאמים אישית. עם בסיס של 400 מיליארד פתיחות PDF בשנה, Adobe ממצבת את עצמה כמובילה בעידן שיתוף המידע הדינמי.",
    "summary": "Adobe מהפכת את עולם ה-PDF with PDF Spaces – סביבת עבודה חדשה המשלבת קבצים, הערות וקישורים לחוויות אינטראקטיביות עם עוזרי AI מותאמים אישית. עם בסיס של 400 מיליארד פתיחות PDF בשנה, Adobe ממצבת את עצמה כמובילה בעידן שיתוף המידע הדינמי.",
    "audience": "אנשי עסקים, יוצרי תוכן ומשתמשי Acrobat",
    "target_audience": "אנשי עסקים, יוצרי תוכן ומשתמשי Acrobat",
    "target": "אנשי עסקים, יוצרי תוכן ומשתמשי Acrobat",
    "link": "https://www.marketingprofs.com/opinions/2026/54655/ai-update-may-8-2026-ai-news-and-views-from-the-past-week",
    "url": "https://www.marketingprofs.com/opinions/2026/54655/ai-update-may-8-2026-ai-news-and-views-from-the-past-week"
  },
  {
    "type": "כלי AI לשיווק",
    "category": "כלי AI לשיווק",
    "source_site": "solutionsreview.com",
    "source": "solutionsreview.com",
    "site": "solutionsreview.com",
    "title": "Clutch AI Visibility Dashboard: הכלי הראשון שמודד איך העסק שלך נראה בתוצאות AI",
    "description": "Clutch השיקה את AI Visibility Dashboard – הכלי הראשון מסוגו שמאפשר לספקי שירותי B2B להבין ולשפר את הנוכחות שלהם בתוצאות חיפוש מבוססות AI. בעידן שבו ChatGPT ו-Gemini מחליפים את גוגל כנקודת הכניסה לחיפוש, הכלי הזה הופך לחיוני לכל עסק.",
    "summary": "Clutch השיקה את AI Visibility Dashboard – הכלי הראשון מסוגו שמאפשר לספקי שירותי B2B להבין ולשפר את הנוכחות שלהם בתוצאות חיפוש מבוססות AI. בעידן שבו ChatGPT ו-Gemini מחליפים את גוגל כנקודת הכניסה לחיפוש, הכלי הזה הופך לחיוני לכל עסק.",
    "audience": "משווקים, מנהלי SEO ועסקי B2B",
    "target_audience": "משווקים, מנהלי SEO ועסקי B2B",
    "target": "משווקים, מנהלי SEO ועסקי B2B",
    "link": "https://solutionsreview.com/ai-news-for-the-week-of-may-8-updates-from-anthropic-cribl-ibm-more/",
    "url": "https://solutionsreview.com/ai-news-for-the-week-of-may-8-updates-from-anthropic-cribl-ibm-more/"
  },
  {
    "type": "עדכון מנוע חיפוש",
    "category": "עדכון מנוע חיפוש",
    "source_site": "cnn.com",
    "source": "cnn.com",
    "site": "cnn.com",
    "title": "גוגל מהפכת את החיפוש: סוכני AI סורקים את הרשת במקומך",
    "description": "גוגל מכריזה על השינוי הגדול ביותר בחיפוש מזה שנים: סוכני AI שסורקים את האינטרנט באופן אוטונומי, ו-Spark – סוכן חדש ב-Gemini שמבצע משימות רקע חוזרות. זו לא עוד תיבת חיפוש – זה עוזר אישי שעובד בשבילך ברקע.",
    "summary": "גוגל מכריזה על השינוי הגדול ביותר בחיפוש מזה שנים: סוכני AI שסורקים את האינטרנט באופן אוטונומי, ו-Spark – סוכן חדש ב-Gemini שמבצע משימות רקע חוזרות. זו לא עוד תיבת חיפוש – זה עוזר אישי שעובד בשבילך ברקע.",
    "audience": "משתמשי גוגל, מפתחים ואנשי שיווק דיגיטלי",
    "target_audience": "משתמשי גוגל, מפתחים ואנשי שיווק דיגיטלי",
    "target": "משתמשי גוגל, מפתחים ואנשי שיווק דיגיטלי",
    "link": "https://www.cnn.com/2026/05/19/tech/google-search-bar-updates-2026",
    "url": "https://www.cnn.com/2026/05/19/tech/google-search-bar-updates-2026"
  },
  {
    "type": "עדכון פלטפורמה ארגונית",
    "category": "עדכון פלטפורמה ארגונית",
    "source_site": "datanorth.ai",
    "source": "datanorth.ai",
    "site": "datanorth.ai",
    "title": "Microsoft Agent 365 ו-E7: חבילת ה-AI הארגונית שמשנה את כללי המשחק",
    "description": "Microsoft השיקה ב-1 במאי 2026 את Agent 365 ואת חבילת E7 החדשה, הכוללת E5, Copilot, Agent 365 ו-Entra Suite. הכלי המרכזי: multi-model orchestration – תיאום בין מודלי AI מרובים לביצוע משימות ארגוניות מורכבות. זו הצעת הערך הארגונית הגדולה ביותר של מיקרוסופט בעידן ה-AI.",
    "summary": "Microsoft השיקה ב-1 במאי 2026 את Agent 365 ואת חבילת E7 החדשה, הכוללת E5, Copilot, Agent 365 ו-Entra Suite. הכלי המרכזי: multi-model orchestration – תיאום בין מודלי AI מרובים לביצוע משימות ארגוניות מורכבות. זו הצעת הערך הארגונית הגדולה ביותר של מיקרוסופט בעידן ה-AI.",
    "audience": "מנהלי IT, CTO ומקבלי החלטות ארגוניים",
    "target_audience": "מנהלי IT, CTO ומקבלי החלטות ארגוניים",
    "target": "מנהלי IT, CTO ומקבלי החלטות ארגוניים",
    "link": "https://datanorth.ai/blog/top-10-ai-tools-for-2026",
    "url": "https://datanorth.ai/blog/top-10-ai-tools-for-2026"
  }
];

const lastUpdatedTime = "01/06/2026, 08:50";